### PR TITLE
Update missing event.item_id and add SCHEDULED/DEADLINE timestamps

### PR DESCRIPTION
**Pull request by lytex**
Instead I'm getting it from `event.id`

Tested under Python 3.8

I've also added a requirements.txt

### CODE REVIEW

**Comment by lytex** [comment]
I've also optional added SCHEDULED and DEADLINE timeestamp ranges so that these events appear in the agenda

**Review by novoid — CHANGES_REQUESTED** [review]
Is it common to specify one single exact version number and not a minimum version with >= ?

**Comment by lytex** [comment]
I think requirements.txt are pretty standard, and since all versions are pinned they should be completely reproducible in another environment. I generated using `pip list --format=freeze > requirements.txt`

To achieve upgradeability, I use [pip-tools](https://pypi.org/project/pip-tools/) to maintain a separate `requirements.in` which states only which packages you import (i.e. not their dependencies), at first without version, unless you need an specific version as you said (e.g. `pandas>=1.0.0`).

I like to at least maintain one `requirements.txt` so that the original environment is reproducible, and once you got that, then use the `requirements.in` to list all the packages you import, but maybe this is too much. What do you think?

**Comment by novoid** [comment]
> What do you think?

I honestly don't have that much experience with Python package management, unfortunately.

I just find it weird when every package comes with its own version of a library. I understand that package version pinning avoids regression issues after lib upgrades. Since I don't have any better idea (or experience) and requirements being an optional thing to have, I'll accept your pull request as is.

_For your information: I'm currently not using the tool (any more) since my current employer fortunately doesn't run any Exchange setup._ 

However, I'm very grateful for your contribution!

**Pull request merged**
